defmodule Ramblings.LLM do
  @moduledoc """
  Module for interacting with LLM services to generate HTML from natural language prompts.
  """

  @doc """
  Generates HTML content from a natural language prompt describing a website.

  ## Examples

      iex> Ramblings.LLM.generate_html("a simple blog about cats")
      {:ok, "<html>...</html>"}

  """
  def generate_html(prompt) do
    # TODO: Replace with actual LLM API call (e.g., Anthropic Claude, OpenAI)
    # For now, return a stubbed HTML response based on the prompt

    html = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Generated from: #{String.slice(prompt, 0..50)}</title>
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                max-width: 800px;
                margin: 0 auto;
                padding: 2rem;
                line-height: 1.6;
                color: #333;
            }
            h1 { color: #2563eb; }
            .prompt {
                background: #f3f4f6;
                padding: 1rem;
                border-radius: 0.5rem;
                margin: 1rem 0;
                font-style: italic;
            }
            .content {
                background: white;
                padding: 2rem;
                border-radius: 0.5rem;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            }
        </style>
    </head>
    <body>
        <h1>✨ Your Generated Website</h1>
        <div class="prompt">
            <strong>Based on your prompt:</strong> "#{prompt}"
        </div>
        <div class="content">
            <h2>Welcome!</h2>
            <p>This is a placeholder website generated from your description.</p>
            <p>In production, this would be a fully-formed HTML page created by an LLM based on your prompt.</p>
            <h3>What you asked for:</h3>
            <p>#{prompt}</p>
            <h3>Features to implement:</h3>
            <ul>
                <li>Connect to Claude or GPT-4 API</li>
                <li>Generate semantic HTML based on prompt</li>
                <li>Add appropriate styling and interactivity</li>
                <li>Handle edge cases and validation</li>
            </ul>
        </div>
        <footer style="margin-top: 2rem; text-align: center; color: #666;">
            <p>Generated by ramblings.cc 🌀</p>
        </footer>
    </body>
    </html>
    """

    # Simulate a small delay like an API call would have
    Process.sleep(500)

    {:ok, html}
  end

  @doc """
  Async version of generate_html that can be used in LiveView processes.
  Returns immediately and sends a message when complete.
  """
  def generate_html_async(prompt, caller_pid) do
    Task.start(fn ->
      case generate_html(prompt) do
        {:ok, html} ->
          send(caller_pid, {:llm_result, :ok, html})

        {:error, reason} ->
          send(caller_pid, {:llm_result, :error, reason})
      end
    end)
  end
end
